// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/protobuf/MessageSend.proto
// Protobuf Java Version: 4.32.1

package org.markus.rhserver.protobuf;

@com.google.protobuf.Generated
public final class MessageSendOuterClass extends com.google.protobuf.GeneratedFile {
  private MessageSendOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 1,
      /* suffix= */ "",
      MessageSendOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MessageSend_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MessageSend_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#src/main/protobuf/MessageSend.proto\"t\n" +
      "\013MessageSend\022\016\n\006sender\030\001 \001(\t\022\020\n\010receiver" +
      "\030\002 \001(\t\022\032\n\004type\030\003 \001(\0162\014.MessageType\022\017\n\007co" +
      "ntent\030\004 \001(\014\022\026\n\002to\030\005 \001(\0162\n.MessageTo*z\n\013M" +
      "essageType\022\010\n\004TEXT\020\000\022\010\n\004FILE\020\001\022\t\n\005IMAGE\020" +
      "\002\022\t\n\005AUDIO\020\003\022\t\n\005VIDEO\020\004\022\017\n\013FILE_SUFFIX\020\005" +
      "\022\t\n\005APPLY\020\006\022\013\n\007OFFLINE\020\007\022\r\n\tHEARTBEAT\020\010*" +
      " \n\tMessageTo\022\010\n\004USER\020\000\022\t\n\005GROUP\020\001B#\n\034org" +
      ".markus.rhserver.protobufP\001\240\001\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_MessageSend_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MessageSend_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_MessageSend_descriptor,
        new java.lang.String[] { "Sender", "Receiver", "Type", "Content", "To", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
