// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/protobuf/MessageSend.proto
// Protobuf Java Version: 4.32.1

package org.markus.rhserver.protobuf;

/**
 * Protobuf enum {@code MessageType}
 */
@com.google.protobuf.Generated
public enum MessageType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>TEXT = 0;</code>
   */
  TEXT(0),
  /**
   * <code>FILE = 1;</code>
   */
  FILE(1),
  /**
   * <code>IMAGE = 2;</code>
   */
  IMAGE(2),
  /**
   * <code>AUDIO = 3;</code>
   */
  AUDIO(3),
  /**
   * <code>VIDEO = 4;</code>
   */
  VIDEO(4),
  /**
   * <code>FILE_SUFFIX = 5;</code>
   */
  FILE_SUFFIX(5),
  /**
   * <code>APPLY = 6;</code>
   */
  APPLY(6),
  /**
   * <code>OFFLINE = 7;</code>
   */
  OFFLINE(7),
  /**
   * <code>HEARTBEAT = 8;</code>
   */
  HEARTBEAT(8),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 1,
      /* suffix= */ "",
      MessageType.class.getName());
  }
  /**
   * <code>TEXT = 0;</code>
   */
  public static final int TEXT_VALUE = 0;
  /**
   * <code>FILE = 1;</code>
   */
  public static final int FILE_VALUE = 1;
  /**
   * <code>IMAGE = 2;</code>
   */
  public static final int IMAGE_VALUE = 2;
  /**
   * <code>AUDIO = 3;</code>
   */
  public static final int AUDIO_VALUE = 3;
  /**
   * <code>VIDEO = 4;</code>
   */
  public static final int VIDEO_VALUE = 4;
  /**
   * <code>FILE_SUFFIX = 5;</code>
   */
  public static final int FILE_SUFFIX_VALUE = 5;
  /**
   * <code>APPLY = 6;</code>
   */
  public static final int APPLY_VALUE = 6;
  /**
   * <code>OFFLINE = 7;</code>
   */
  public static final int OFFLINE_VALUE = 7;
  /**
   * <code>HEARTBEAT = 8;</code>
   */
  public static final int HEARTBEAT_VALUE = 8;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static MessageType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static MessageType forNumber(int value) {
    switch (value) {
      case 0: return TEXT;
      case 1: return FILE;
      case 2: return IMAGE;
      case 3: return AUDIO;
      case 4: return VIDEO;
      case 5: return FILE_SUFFIX;
      case 6: return APPLY;
      case 7: return OFFLINE;
      case 8: return HEARTBEAT;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      MessageType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
          public MessageType findValueByNumber(int number) {
            return MessageType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return org.markus.rhserver.protobuf.MessageSendOuterClass.getDescriptor().getEnumTypes().get(0);
  }

  private static final MessageType[] VALUES = values();

  public static MessageType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private MessageType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:MessageType)
}

