// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/protobuf/MessageSend.proto
// Protobuf Java Version: 4.32.1

package org.markus.rhserver.protobuf;

/**
 * Protobuf enum {@code MessageTo}
 */
@com.google.protobuf.Generated
public enum MessageTo
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>USER = 0;</code>
   */
  USER(0),
  /**
   * <code>GROUP = 1;</code>
   */
  GROUP(1),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 32,
      /* patch= */ 1,
      /* suffix= */ "",
      MessageTo.class.getName());
  }
  /**
   * <code>USER = 0;</code>
   */
  public static final int USER_VALUE = 0;
  /**
   * <code>GROUP = 1;</code>
   */
  public static final int GROUP_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static MessageTo valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static MessageTo forNumber(int value) {
    switch (value) {
      case 0: return USER;
      case 1: return GROUP;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<MessageTo>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      MessageTo> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<MessageTo>() {
          public MessageTo findValueByNumber(int number) {
            return MessageTo.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return org.markus.rhserver.protobuf.MessageSendOuterClass.getDescriptor().getEnumTypes().get(1);
  }

  private static final MessageTo[] VALUES = values();

  public static MessageTo valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private MessageTo(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:MessageTo)
}

