// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/protobuf/MessageSend.proto
// Protobuf Java Version: 4.32.1

package org.markus.rhserver.protobuf;

@com.google.protobuf.Generated
public interface MessageSendOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MessageSend)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sender = 1;</code>
   * @return The sender.
   */
  java.lang.String getSender();
  /**
   * <code>string sender = 1;</code>
   * @return The bytes for sender.
   */
  com.google.protobuf.ByteString
      getSenderBytes();

  /**
   * <code>string receiver = 2;</code>
   * @return The receiver.
   */
  java.lang.String getReceiver();
  /**
   * <code>string receiver = 2;</code>
   * @return The bytes for receiver.
   */
  com.google.protobuf.ByteString
      getReceiverBytes();

  /**
   * <code>.MessageType type = 3;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.MessageType type = 3;</code>
   * @return The type.
   */
  org.markus.rhserver.protobuf.MessageType getType();

  /**
   * <code>bytes content = 4;</code>
   * @return The content.
   */
  com.google.protobuf.ByteString getContent();

  /**
   * <code>.MessageTo to = 5;</code>
   * @return The enum numeric value on the wire for to.
   */
  int getToValue();
  /**
   * <code>.MessageTo to = 5;</code>
   * @return The to.
   */
  org.markus.rhserver.protobuf.MessageTo getTo();
}
